int_putchar(char c);
void print_alphabet(void);
void Print_alphabet_x10(void);
int_islower(char c);
int_isalpha(char c);
int print_sign(int n);
int_abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
